# Generated by Django 4.2.5 on 2023-10-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_shippingaddress_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
    ]
